#resources:
#  repositories:
#  - repository: portable-stimulus
#    type: github
#    endpoint: PSSTools
#    name: mballance/portable-stimulus
trigger:
- master

jobs:
- job: Linux
  pool:
   vmImage: 'ubuntu-latest'

  variables:
  - name: build_num
    value: $(Build.BuildNumber)

  steps:
#  - checkout: self
#  - checkout: portable-stimulus
#    path: sys/portable-stimulus
#
#  - script: |
#      git -c http.https://github.com/mballance/portable-stimulus.extraheader="AUTHORIZATION: basic $(GITAUTH)" clone https://github.com/mballance/portable-stimulus sys/portable-stimulus
#    displayName: 'Checkout examples'

  - script: |
      sudo apt-get update
      sudo apt-get install default-jdk
    displayName: 'Install JDK'
  - script: |
      python3 -m pip install wheel twine
      python3 -m pip install ivpm
    displayName: 'Install Python tools'
  - script: |
      ivpm update
    displayName: 'Fetch dependencies'
  - script: |
      mkdir build
      cd build
      cmake ..
      make -j`nproc`
    displayName: 'Build'


    
