"""No ``dynamic_cast`` on AST nodes in ``src/``: use ``NodeKind``.

The AST interfaces inherit ``public virtual``, so a ``dynamic_cast`` on one
walks the base-class graph and compares type names with ``strcmp`` -- about
1,900 instructions, and a failing cast is the worst case. Before NodeKind
(2026-09-27) it was ~95% of link time: link went from 9.94G instructions to
0.95G when every cast was converted.

``NodeKind`` (``src/include/pssp/impl/NodeKind.h``, generated by
``scripts/gen_node_kind.py``) answers the same question with one virtual
dispatch and a switch::

    ast::IFoo *f = NodeKind::cast<ast::IFoo>(node);   // one question

    NodeKind nk(node);                                // several on one node
    if (ast::IFoo *f = nk.as<ast::IFoo>()) ...
    else if (nk.is<ast::IBar>()) ...

Build with ``PSSP_NODEKIND_CHECK`` defined to check every answer against
``dynamic_cast`` (see the plan's §11 entry of 2026-09-27).
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"

_CAST = re.compile(r"dynamic_cast\s*<\s*(?:const\s+)?(?:pssp::)?ast::")

#: NodeKind's own check mode is the one place that compares against
#: dynamic_cast.
_SKIP_FILES = {"NodeKind.h"}

#: Generated or third-party code under src/ that this project does not own.
_SKIP_DIRS = {"antlr4", "gen"}


def _offenders():
    out = []
    for p in sorted(list(SRC.rglob("*.cpp")) + list(SRC.rglob("*.h"))):
        if p.name in _SKIP_FILES or _SKIP_DIRS.intersection(p.relative_to(SRC).parts):
            continue
        for n, line in enumerate(p.read_text(errors="replace").splitlines(), 1):
            code = line.split("//", 1)[0]
            if _CAST.search(code):
                out.append("%s:%d: %s" % (p.relative_to(ROOT), n, line.strip()))
    return out


def test_no_dynamic_cast_on_ast_nodes():
    offenders = _offenders()
    assert not offenders, (
        "dynamic_cast on an AST node; use NodeKind::cast<T>(n), or a NodeKind "
        "for several questions on one node (see this test's docstring):\n  "
        + "\n  ".join(offenders))
