#!/usr/bin/env python3
"""Record the AST the native Python parser builds, as a fixture for the TS tests.

    packages/python/bin/python ts/scripts/gen-ast-parity-fixture.py \\
        -o ts/test/fixtures/ast-parity.json

Companion to gen-parity-fixture.py, which does the same for markers, and the
reasoning is identical: expectations are *generated by running the real parser*
rather than written by hand, because a hand-written expectation only shows that
the WASM core agrees with what the author believed while reading the same source
twice.

What is recorded is the **declaration spine** -- the pre-order walk that
`ASTUtils.walkScope` performs, which descends through `Scope` and through
`SymbolChildrenScope` and through nothing else -- with each node's class name,
declared name and location.  The Python walk below is a deliberate transliteration
of that function; if the two drift, the fixture stops meaning what it claims.

**What this does not cover, and why it is still worth having.**  The spine is
the containment structure and the fields on it; it does not descend into
expressions, constraints or exec bodies, so a serialisation defect confined to
`ExprBin.op` would not appear here.  What it does catch is the class of defect
the wire format is most exposed to: a node built as the wrong class, a subtree
attached at the wrong place, a location field transposed with another location
field.  Those are invisible to a round-trip test -- both halves are generated
from one schema, so they agree with each other whether or not they agree with
the AST -- and this is the only test in Phase 2 that has independent ground
truth.  The full-tree gate is Phase 3's (`ts-wasm-impl-plan.md`).
"""

import argparse
import json
import os
import sys


def spine(scope, ast):
    """The pre-order walk of `ASTUtils.walkScope`, flattened.

    Depth is recorded per entry rather than nesting the JSON: the TypeScript
    side compares two flat sequences, and a flat sequence makes the *first*
    divergence legible in a diff instead of a reshaped subtree.
    """
    out = []

    def children_of(node):
        # ASTUtils.childrenOf. Two unrelated container classes -- neither is an
        # ancestor of the other, and testing only for Scope silently skips every
        # activity body.
        if isinstance(node, (ast.Scope, ast.SymbolChildrenScope)):
            return list(node.children())
        return []

    def name_of(node):
        # ASTUtils.getNodeName. Two unrelated named forms, likewise.
        if isinstance(node, (ast.NamedScope, ast.NamedScopeChild)):
            n = node.getName()
            return n.getId() if n is not None else None
        return None

    def visit(node, depth):
        loc = node.getLocation()
        out.append([
            type(node).__name__,
            name_of(node),
            depth,
            loc.fileid, loc.lineno, loc.linepos, loc.extent,
        ])
        for c in children_of(node):
            visit(c, depth + 1)

    for child in scope.children():
        visit(child, 0)

    return out


def run_case(case, ast):
    """Parse one case and record the spine of every unit it produced.

    A case whose parse fails contributes no units, and is recorded as such
    rather than skipped: "this source produces no AST" is itself an expectation
    the WASM side has to match.
    """
    from pssparser.parser import Parser

    parser = Parser()
    raised = None
    try:
        parser.parses(list(case["files"]))
    except Exception as e:
        raised = type(e).__name__

    # parser._files is the unit list, standard library at index 0. Reached
    # directly because the public API exposes units only after link(), and
    # linking would fold them into the symbol tree -- a different structure from
    # the one the serialiser is being checked against.
    units = []
    if raised is None:
        for i, unit in enumerate(parser._files):
            units.append({"fileid": i, "spine": spine(unit, ast)})

    return {
        "id": case["id"],
        "why": case.get("why", ""),
        "files": [{"name": n, "content": c} for n, c in case["files"]],
        "raised": raised,
        "units": units,
    }


#: Inline cases chosen for the schema features they exercise, not for coverage
#: of PSS. Each names the wire-format construct it puts under test.
INLINE_CASES = [
    {
        "id": "minimal",
        "why": "a component and an action: the smallest real containment spine",
        "files": [("top.pss", "component pss_top {\n    action A { }\n}\n")],
    },
    {
        "id": "nested-scopes",
        "why": "four levels of nesting, so a subtree attached one level off shows up",
        "files": [("nest.pss",
                   "package p {\n"
                   "    component c {\n"
                   "        action a {\n"
                   "            activity {\n"
                   "                repeat (3) { }\n"
                   "            }\n"
                   "        }\n"
                   "    }\n"
                   "}\n")],
    },
    {
        "id": "activity-body",
        "why": (
            "an activity body hangs off SymbolChildrenScope, not Scope. This is "
            "the case a traversal that tests only `instanceof Scope` drops, and "
            "the serialiser walks ownership rather than either, so a mismatch "
            "between the two shows here first."
        ),
        "files": [("act.pss",
                   "component pss_top {\n"
                   "    action A { }\n"
                   "    action B {\n"
                   "        activity {\n"
                   "            do A;\n"
                   "            do A;\n"
                   "        }\n"
                   "    }\n"
                   "}\n")],
    },
    {
        "id": "many-fields",
        "why": "scalar fields of several widths on one class, adjacent in the buffer",
        "files": [("fields.pss",
                   "component pss_top {\n"
                   "    action A {\n"
                   "        rand bit[7:0] b;\n"
                   "        rand int in [1..10] i;\n"
                   "        rand bool flag;\n"
                   "        rand string s;\n"
                   "    }\n"
                   "}\n")],
    },
    {
        "id": "enum-and-flags",
        "why": "enum-typed and flags-typed fields, both written as i32",
        "files": [("enums.pss",
                   "component pss_top {\n"
                   "    enum e_t { A, B, C };\n"
                   "    action A {\n"
                   "        rand e_t e;\n"
                   "        static const int K = 3;\n"
                   "    }\n"
                   "}\n")],
    },
    {
        "id": "unicode-strings",
        "why": (
            "string fields are length-prefixed UTF-8 on both sides. A byte "
            "length read as a character count truncates exactly here and "
            "nowhere in ASCII."
        ),
        "files": [("uni.pss",
                   "component pss_top {\n"
                   "    /** éèê 你好 \U0001f600 */\n"
                   "    action A { }\n"
                   "}\n")],
    },
    {
        "id": "empty-scope",
        "why": "a zero-length child list: the count prefix with nothing after it",
        "files": [("empty.pss", "package p { }\n")],
    },
]


def corpus_cases(corpus_dir):
    cases = []
    for dirpath, _, filenames in os.walk(corpus_dir):
        for fn in sorted(filenames):
            if not fn.endswith(".pss"):
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, corpus_dir).replace(os.sep, "/")
            with open(path, "r", encoding="utf-8", errors="replace") as fp:
                content = fp.read()
            cases.append({
                "id": "corpus:" + rel,
                "why": "corpus AST parity",
                "files": [(rel, content)],
            })
    return sorted(cases, key=lambda c: c["id"])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--corpus", help="directory of .pss files to include")
    ap.add_argument("--no-corpus", action="store_true")
    ap.add_argument("--stdlib", action="store_true", default=True,
                    help="include unit 0, the standard library (default)")
    ap.add_argument("--no-stdlib", dest="stdlib", action="store_false")
    args = ap.parse_args(argv)

    try:
        import pssparser.ast as ast
        import pssparser.parser  # noqa: F401
    except ImportError as e:
        raise SystemExit(
            "cannot import pssparser (%s).\n"
            "Build the native extension first:\n"
            "    packages/python/bin/python setup.py build_ext --inplace\n"
            "and run this with PYTHONPATH=python." % e)

    cases = list(INLINE_CASES)
    corpus = None
    if not args.no_corpus:
        corpus = args.corpus or os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..", "..", "packages", "pss-corpus", "curated")
        corpus = os.path.abspath(corpus)
        if os.path.isdir(corpus):
            cases.extend(corpus_cases(corpus))
        else:
            print("no corpus at %s -- inline cases only" % corpus, file=sys.stderr)
            corpus = None

    results = []
    for c in cases:
        r = run_case(c, ast)
        if not args.stdlib:
            r["units"] = [u for u in r["units"] if u["fileid"] != 0]
        else:
            # Unit 0 is the same tree in every case, and it is the largest one
            # here. Recorded once, on the first case that produced it, and
            # elided everywhere else -- 92 identical copies would dominate the
            # fixture and say nothing 1 copy does not.
            if any("stdlib" in prev.get("_carries", "") for prev in results):
                r["units"] = [u for u in r["units"] if u["fileid"] != 0]
            elif any(u["fileid"] == 0 for u in r["units"]):
                r["_carries"] = "stdlib"
        results.append(r)

    out = {
        "generator": "ts/scripts/gen-ast-parity-fixture.py",
        "note": (
            "Generated from the native pssparser Python bindings. Do not edit by "
            "hand -- regenerate. Each unit's `spine` is the pre-order walk of "
            "ASTUtils.walkScope: [class, name, depth, fileid, lineno, linepos, "
            "extent]. Unit 0 (the standard library) is recorded on one case only; "
            "it is identical in all of them."),
        "cases": results,
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as fp:
        json.dump(out, fp, indent=1, sort_keys=True)
        fp.write("\n")

    n_nodes = sum(len(u["spine"]) for r in results for u in r["units"])
    print("wrote %s: %d cases, %d spine nodes%s" % (
        args.output, len(results), n_nodes,
        (" (corpus: %s)" % corpus) if corpus else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
