#!/usr/bin/env python3
"""Record what the native Python parser reports, as a fixture for the TS tests.

    packages/python/bin/python ts/scripts/gen-parity-fixture.py \\
        -o ts/test/fixtures/parity.json

The point of the parity test is that the WASM core and the native core agree.
A test asserting against *hand-written* expectations does not show that: it
shows that the WASM core agrees with whatever the author believed, and the
author read the same source both times.  So the expectations are generated by
running the real thing.

This runs at development time, not at test time.  The output is committed, so
the TypeScript suite needs no Python, no native build and no corpus checkout --
which matters because those are exactly the three things a Node developer
cloning this package will not have.  Re-run it when the corpus or the parser's
diagnostics change; the diff is then a reviewable record of what changed.
"""

import argparse
import json
import os
import sys


#: Inline cases, kept beside the corpus rather than in it.
#:
#: The corpus is shared across the estate (pss-corpus/PLAN.md) and is not the
#: place for fixtures that exist to pin one parser's diagnostics.  Each case
#: here targets a specific claim in ts-api-design.md.
INLINE_CASES = [
    {
        "id": "valid-minimal",
        "why": "a valid source parses with zero markers",
        "files": [("top.pss", "component pss_top {\n    action A { }\n}\n")],
    },
    {
        "id": "syntax-error",
        "why": "line/col/message/code of a syntax error (impl plan §1.7 test 2)",
        "files": [("bad.pss", "component pss_top { action }")],
    },
    {
        "id": "stdlib-visible",
        "why": (
            "the standard library is loaded without being asked for "
            "(ts-api-design.md §3.2.1). `executor_claim_s` is declared in the "
            "stdlib, so this resolves only if unit 0 was loaded."
        ),
        "files": [
            (
                "uses_stdlib.pss",
                "component pss_top {\n"
                "    action A {\n"
                "        executor_claim_s<> claim;\n"
                "    }\n"
                "}\n",
            )
        ],
    },
    {
        "id": "multi-file",
        "why": (
            "fileids are assigned from 1 in parse order, and a marker in the "
            "second file reports the second file's name"
        ),
        "files": [
            ("a.pss", "package p {\n    const int K = 4;\n}\n"),
            ("b.pss", "component pss_top {\n    action }\n}\n"),
        ],
    },
    {
        "id": "cross-unit-constant",
        "why": (
            "one builder serves both calls, so the second source sees the "
            "first source's compile-time constants (ts-api-design.md §3.2.2). "
            "Two separate parseSources() calls, deliberately."
        ),
        "calls": [
            [("consts.pss", "package p {\n    const int W = 8;\n}\n")],
            [
                (
                    "uses.pss",
                    "import p::*;\ncomponent pss_top {\n"
                    "    action A {\n        rand bit[p::W] f;\n    }\n}\n",
                )
            ],
        ],
    },
    {
        "id": "max-errors",
        "why": "setMaxErrors(1) caps error markers and adds the PSS029 notice",
        "max_errors": 1,
        "files": [("many.pss", "component c { action } action } action }\n")],
    },
]


def run_case(case):
    """Parse one case and return its markers, whatever the outcome."""
    from pssparser.parser import Parser

    parser = Parser()
    if case.get("max_errors"):
        parser.set_max_errors(case["max_errors"])

    calls = case.get("calls") or [case["files"]]

    raised = None
    for files in calls:
        try:
            parser.parses(list(files))
        except Exception as e:  # ParseException, and anything else is a finding
            raised = type(e).__name__
            break

    return {
        "id": case["id"],
        "why": case.get("why", ""),
        "calls": [[{"name": n, "content": c} for n, c in files] for files in calls],
        "maxErrors": case.get("max_errors", 0),
        "raised": raised,
        "markers": parser.markers,
    }


def corpus_cases(corpus_dir):
    """One case per .pss file under *corpus_dir*, named by its relative path."""
    cases = []
    for dirpath, _, filenames in os.walk(corpus_dir):
        for fn in sorted(filenames):
            if not fn.endswith(".pss"):
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, corpus_dir)
            with open(path, "r", encoding="utf-8", errors="replace") as fp:
                content = fp.read()
            cases.append({
                "id": "corpus:" + rel.replace(os.sep, "/"),
                "why": "corpus parity",
                "files": [(rel.replace(os.sep, "/"), content)],
            })
    return sorted(cases, key=lambda c: c["id"])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--corpus", help="directory of .pss files to include")
    ap.add_argument("--no-corpus", action="store_true")
    args = ap.parse_args(argv)

    try:
        import pssparser.parser  # noqa: F401
    except ImportError as e:
        raise SystemExit(
            "cannot import pssparser (%s).\n"
            "Build the native extension first:\n"
            "    packages/python/bin/python setup.py build_ext --inplace\n"
            "and run this with PYTHONPATH=python." % e
        )

    cases = list(INLINE_CASES)
    corpus = None
    if not args.no_corpus:
        corpus = args.corpus or os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..", "..", "packages", "pss-corpus", "curated")
        corpus = os.path.abspath(corpus)
        if os.path.isdir(corpus):
            cases.extend(corpus_cases(corpus))
        else:
            print("no corpus at %s -- inline cases only" % corpus, file=sys.stderr)
            corpus = None

    results = [run_case(c) for c in cases]

    out = {
        # Deliberately no timestamp and no absolute paths: this file is
        # committed, and a regeneration that changed nothing should produce an
        # empty diff. A timestamp would make every regeneration look like a
        # change to the parser's behaviour.
        "generator": "ts/scripts/gen-parity-fixture.py",
        "note": (
            "Generated from the native pssparser Python bindings. "
            "Do not edit by hand -- regenerate. See the module docstring for why "
            "these expectations are generated rather than written."
        ),
        "cases": results,
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as fp:
        json.dump(out, fp, indent=1, sort_keys=True)
        fp.write("\n")

    n_markers = sum(len(r["markers"]) for r in results)
    print("wrote %s: %d cases, %d markers%s" % (
        args.output, len(results), n_markers,
        (" (corpus: %s)" % corpus) if corpus else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
