"""Type stubs for :mod:`pssparser.cst`.

Hand-written, because ``Cst`` and ``CstNode`` are defined in the Cython
``core`` extension and a type checker cannot see into it.
"""

from typing import Any, Iterator, Optional, Tuple, Union

from .tokens import Token, TokenStream

class CstNode:
    @property
    def is_rule(self) -> bool: ...
    @property
    def is_error(self) -> bool: ...
    @property
    def rule_index(self) -> int: ...
    @property
    def rule_name(self) -> str: ...
    @property
    def token_index(self) -> int: ...
    @property
    def token(self) -> Optional[Token]: ...
    @property
    def num_children(self) -> int: ...
    @property
    def children(self) -> Tuple["CstNode", ...]: ...
    @property
    def start_token(self) -> int: ...
    @property
    def stop_token(self) -> int: ...
    @property
    def text(self) -> str: ...
    def walk(self) -> Iterator["CstNode"]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> "CstNode": ...
    def __iter__(self) -> Iterator["CstNode"]: ...

class Cst:
    tokens: TokenStream
    num_syntax_errors: int

    @property
    def root(self) -> Optional[CstNode]: ...
    @property
    def text(self) -> str: ...

def parse(src: Union[str, bytes, bytearray, Any]) -> Cst: ...
