/**
 * The WASM core and the native core must report the same diagnostics.
 *
 * This is Phase 1's real deliverable (`ts-wasm-impl-plan.md` §1.7 test 2): the
 * first evidence that compiling the C++ core to WebAssembly did not change
 * what it says about a program.
 *
 * The expectations are **not written here**. They are in
 * `test/fixtures/parity.json`, generated by running the native Python bindings
 * over the same inputs (`scripts/gen-parity-fixture.py`). A hand-written
 * expectation would only show that the WASM core agrees with what the author
 * believed while reading the same source twice.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { createParser, ParseException, type Marker } from '../src/index.js';

interface FixtureCase {
  id: string;
  why: string;
  calls: Array<Array<{ name: string; content: string }>>;
  maxErrors: number;
  raised: string | null;
  markers: Marker[];
}

const fixturePath = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'parity.json');
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as {
  cases: FixtureCase[];
};

/**
 * Run one fixture case through the WASM parser exactly as the generator ran it
 * through the native one.
 */
async function runCase(c: FixtureCase): Promise<{ markers: readonly Marker[]; raised: boolean }> {
  const parser = await createParser();
  try {
    if (c.maxErrors) {
      parser.setMaxErrors(c.maxErrors);
    }
    let raised = false;
    for (const call of c.calls) {
      try {
        parser.parseSources(call);
      } catch (e) {
        if (!(e instanceof ParseException)) throw e;
        raised = true;
        // The generator stops at the first raising call, so this must too.
        break;
      }
    }
    return { markers: parser.markers, raised };
  } finally {
    parser.dispose();
  }
}

const inline = fixture.cases.filter((c) => !c.id.startsWith('corpus:'));
const corpus = fixture.cases.filter((c) => c.id.startsWith('corpus:'));

describe('parity with the native parser: inline cases', () => {
  it.each(inline.map((c) => [c.id, c] as const))('%s', async (_id, c) => {
    const got = await runCase(c);

    // Whether the parse raised is part of the contract, not an incidental:
    // parseSources throws exactly when an error-severity marker was produced.
    expect(got.raised, `${c.id}: raised (${c.why})`).toBe(c.raised !== null);

    // Compared whole rather than field by field. Every field is specified --
    // severity, message, file, line, col, extent, related, code -- and
    // comparing a subset is how a difference in the unchecked field survives.
    expect(got.markers, c.why).toEqual(c.markers);
  });
});

describe('parity with the native parser: corpus', () => {
  it.each(corpus.map((c) => [c.id.slice('corpus:'.length), c] as const))(
    '%s',
    async (_name, c) => {
      const got = await runCase(c);
      expect(got.markers).toEqual(c.markers);
      expect(got.raised).toBe(c.raised !== null);
    }
  );

  it('covers the corpus rather than a sample of it', () => {
    // A parity suite that silently shrank -- a moved corpus, a generator that
    // wrote nothing -- would keep passing while testing nothing. The number is
    // a floor, not an exact count, so adding corpus files does not fail here.
    expect(corpus.length).toBeGreaterThanOrEqual(80);
  });
});
