#!/usr/bin/env python3
"""Emit the AST schema hash as a C++ header and a TypeScript module.

    gen_schema_hash.py <astdir> [-h out.h] [-t out.ts]

The two halves of the WASM package -- the ``.wasm`` compiled from the C++ AST
and the ``.ts`` classes emitted by ``astbuilder gen-ts`` -- are generated from
the same ``ast/*.yaml`` and must stay in step.  When they do not, fields land
in different slots on the two sides and every downstream symptom is baffling:
a string read as an integer, a child list off by one, a node that deserialises
into the wrong class.  Nothing about the failure points at the build.

So both halves carry the hash of the schema they were generated from, and the
loader compares them (``ts-api-design.md`` §7).  A mismatch is fatal and says
so.  This is the single highest-value piece of defensive code in the design,
and it is cheap: one string comparison at startup.

The hash covers file *names* as well as contents, so adding or removing a spec
file changes it even if the surviving files are untouched.

``ts-api-design.md`` §2 lists ``schema_hash.{h,ts}`` as ``gen_wasm`` output
(impl plan Phase 2).  It lives in its own script instead because the loader
check is a Phase 1 deliverable and does not depend on the serialiser: nothing
here knows anything about the wire format, only about the schema's identity.
"""

import argparse
import hashlib
import os
import sys


def compute(astdir):
    """Hash every ``*.yaml`` under *astdir*, name and content alike."""
    files = sorted(f for f in os.listdir(astdir) if f.endswith(".yaml"))
    if not files:
        raise SystemExit("gen_schema_hash: no *.yaml under %s" % astdir)

    h = hashlib.sha256()
    for name in files:
        # The name goes into the digest with an explicit separator so that
        # ("ab", "c") and ("a", "bc") cannot collide.
        h.update(name.encode("utf-8"))
        h.update(b"\0")
        with open(os.path.join(astdir, name), "rb") as fp:
            content = fp.read()
        # Normalise line endings. A Windows checkout with core.autocrlf on
        # would otherwise produce a different hash from a Linux one for byte
        # identical schema content, and the mismatch would be reported as a
        # build skew that does not exist.
        content = content.replace(b"\r\n", b"\n")
        h.update(str(len(content)).encode("ascii"))
        h.update(b"\0")
        h.update(content)

    return h.hexdigest(), files


BANNER = """\
/****************************************************************************
 * %s
 *
 * Generated by scripts/gen_schema_hash.py -- do not edit.
 *
 * Identifies the ast/*.yaml the AST bindings on both sides of the WASM
 * boundary were generated from.  Checked at module load; a mismatch is fatal.
 * Source files (%d):
%s
 ****************************************************************************/
"""


def banner(outname, files):
    listing = "\n".join(" *   %s" % f for f in files)
    return BANNER % (outname, len(files), listing)


def write_if_changed(path, content):
    """Write *content* to *path* only when it differs from what is there.

    The wasm build runs this at cmake *configure* time, and an explicit
    `cmake -S -B` always re-configures. Writing unconditionally made the
    header newer than every object that includes it, turning a no-op refresh
    into a full rebuild.
    """
    try:
        with open(path, "r") as fp:
            if fp.read() == content:
                return False
    except (FileNotFoundError, IsADirectoryError, UnicodeDecodeError):
        pass
    with open(path, "w") as fp:
        fp.write(content)
    return True


def write_header(path, digest, files):
    write_if_changed(path, "".join((
        banner(os.path.basename(path), files),
        "#pragma once\n\n",
        '#define PSSPARSER_AST_SCHEMA_HASH "%s"\n' % digest)))


def write_ts(path, digest, files):
    write_if_changed(path, "".join((
        banner(os.path.basename(path), files),
        "\n/** sha256 of the ast/*.yaml this package was generated from. */\n",
        "export const AST_SCHEMA_HASH = '%s';\n" % digest)))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("astdir", help="directory holding the ast/*.yaml specs")
    ap.add_argument("-H", "--header", help="path to write the C++ header to")
    ap.add_argument("-T", "--typescript", help="path to write the TS module to")
    args = ap.parse_args(argv)

    if not args.header and not args.typescript:
        ap.error("nothing to do: pass -H, -T, or both")

    digest, files = compute(args.astdir)

    for path in (args.header, args.typescript):
        if path:
            parent = os.path.dirname(os.path.abspath(path))
            if parent:
                os.makedirs(parent, exist_ok=True)

    if args.header:
        write_header(args.header, digest, files)
    if args.typescript:
        write_ts(args.typescript, digest, files)

    print("schema hash: %s (%d files)" % (digest, len(files)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
