#!/usr/bin/env python3
"""Generate src/include/pssp/impl/NodeKind.h from the generated AST headers.

NodeKind replaces ``dynamic_cast`` on AST nodes. The AST interfaces inherit
``public virtual``, so on this hierarchy a ``dynamic_cast`` walks the base
graph and compares type names with ``strcmp``: about 1,900 instructions a
cast, and a failing cast is the worst case. It was ~95% of link time.

NodeKind classifies a node with one virtual dispatch. It implements the pure
``ast::IVisitor`` -- not ``VisitorBase``, whose default visits descend into
the node's fields -- and each generated ``visitX(IX *i)`` records the class id
and the node as an ``IX*``. ``as<T>()`` is a generated switch over the
classes derived from ``T`` (``T`` included); each case converts the stored
``IX*`` up to ``T*``, which is free. Downcasting is what virtual inheritance
forbids to ``static_cast``, and what this avoids.

Usage: scripts/gen_node_kind.py [--check]
  --check  exit 1 if the checked-in header is not what would be generated
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AST_INC = ROOT / "build" / "include" / "pssp" / "ast"
OUT = ROOT / "src" / "include" / "pssp" / "impl" / "NodeKind.h"


def load():
    visitor = (AST_INC / "IVisitor.h").read_text()
    classes = re.findall(r"virtual void visit(\w+)\(I\1 \*i\) = 0;", visitor)
    supers = {}
    for c in classes:
        text = (AST_INC / ("I%s.h" % c)).read_text()
        m = re.search(r"^class I%s\s*:\s*public virtual I(\w+)\s*\{" % c, text, re.M)
        supers[c] = m.group(1) if m else None
    return classes, supers


def generate():
    classes, supers = load()
    roots = [c for c in classes if supers[c] is None]
    derived = {c: [] for c in classes}      # T -> classes deriving from T
    root_of = {}
    for c in classes:
        a = c
        while a:
            derived[a].append(c)
            root_of[c] = a
            a = supers[a]

    L = []
    w = L.append
    w("/**")
    w(" * NodeKind.h -- GENERATED by scripts/gen_node_kind.py; do not edit.")
    w(" *")
    w(" * Replaces dynamic_cast on AST nodes: one virtual dispatch, then a switch.")
    w(" * See the script for why.")
    w(" *")
    w(" *     ast::IFoo *f = NodeKind::cast<ast::IFoo>(node);   // one question")
    w(" *")
    w(" *     NodeKind nk(node);                                // several")
    w(" *     if (ast::IFoo *f = nk.as<ast::IFoo>()) ...")
    w(" *     else if (nk.is<ast::IBar>()) ...")
    w(" *     switch (nk.id()) { case NodeKind::Id::Baz: ... }")
    w(" *")
    w(" * With PSSP_NODEKIND_CHECK defined, every as<T>() also runs the")
    w(" * dynamic_cast from the node as it was given, and throws InternalError if")
    w(" * the answers differ.")
    w(" */")
    w("#pragma once")
    w("#include <stdint.h>")
    w('#include "pssp/ast/IVisitor.h"')
    for c in sorted(classes):
        w('#include "pssp/ast/I%s.h"' % c)
    w("#ifdef PSSP_NODEKIND_CHECK")
    w('#include "pssp/impl/InternalError.h"')
    w("#endif")
    w("")
    w("namespace pssp {")
    w("")
    w("template <class T> struct NodeKindAlwaysFalse { static const bool value = false; };")
    w("")
    w("class NodeKind : public ast::IVisitor {")
    w("public:")
    w("    enum class Id : uint16_t {")
    w("        None,")
    for c in classes:
        w("        %s," % c)
    w("    };")
    w("")
    w("    NodeKind() : m_id(Id::None), m_ptr(0) { }")
    for r in roots:
        w("    explicit NodeKind(ast::I%s *n) : m_id(Id::None), m_ptr(0) {" % r)
        w("#ifdef PSSP_NODEKIND_CHECK")
        w("        m_chk_%s = n;" % r)
        w("#endif")
        w("        if (n) {")
        w("            n->accept(this);")
        w("        }")
        w("    }")
    w("")
    w("    virtual ~NodeKind() { }")
    w("")
    w("    /** The node's own class; Id::None for a null node. */")
    w("    Id id() const { return m_id; }")
    w("")
    w("    /** The node as a T, or null if it is not one. */")
    w("    template <class T> T *as() const {")
    w("        static_assert(NodeKindAlwaysFalse<T>::value,")
    w('            "NodeKind::as<T>: T is not an AST class");')
    w("        return 0;")
    w("    }")
    w("")
    w("    template <class T> bool is() const { return as<T>() != 0; }")
    w("")
    w("    /** dynamic_cast<T *>(n), for an AST node `n`. */")
    w("    template <class T, class N> static T *cast(N *n) {")
    w("        return NodeKind(n).as<T>();")
    w("    }")
    w("")
    w("    /** dynamic_cast<const T *>(n). Classifying does not modify `n`. */")
    w("    template <class T, class N> static const T *cast(const N *n) {")
    w("        return NodeKind(const_cast<N *>(n)).as<T>();")
    w("    }")
    w("")
    for c in classes:
        w("    virtual void visit%s(ast::I%s *i) override {" % (c, c))
        w("        m_id = Id::%s;" % c)
        w("        m_ptr = i;")
        w("    }")
    w("")
    w("private:")
    w("    Id              m_id;")
    w("    void            *m_ptr;   // an I<m_id>*, as stored by visit<m_id>")
    w("#ifdef PSSP_NODEKIND_CHECK")
    for r in roots:
        w("    ast::I%s *m_chk_%s = 0;" % (r, r))
    w("")
    w("    template <class T, class R> static T *check(T *ret, R *src) {")
    w("        if (ret != dynamic_cast<T *>(src)) {")
    w('            throw InternalError("NodeKind disagrees with dynamic_cast");')
    w("        }")
    w("        return ret;")
    w("    }")
    w("#endif")
    w("};")
    w("")
    for t in classes:
        w("template <> inline ast::I%s *NodeKind::as<ast::I%s>() const {" % (t, t))
        w("    ast::I%s *ret = 0;" % t)
        if len(derived[t]) == 1:
            w("    if (m_id == Id::%s) {" % t)
            w("        ret = static_cast<ast::I%s *>(m_ptr);" % t)
            w("    }")
        else:
            w("    switch (m_id) {")
            for d in derived[t]:
                w("        case Id::%s: ret = static_cast<ast::I%s *>(m_ptr); break;" % (d, d))
            w("        default: break;")
            w("    }")
        w("#ifdef PSSP_NODEKIND_CHECK")
        w("    if (m_chk_%s) {" % root_of[t])
        w("        check(ret, m_chk_%s);" % root_of[t])
        w("    }")
        w("#endif")
        w("    return ret;")
        w("}")
    w("")
    w("}")
    w("")
    return "\n".join(L)


def main():
    text = generate()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("%s is stale: run scripts/gen_node_kind.py" % OUT)
            return 1
        return 0
    OUT.write_text(text)
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
