#!/bin/bash
#****************************************************************************
#* wasm-env.sh
#*
#* Put the Emscripten toolchain fetched by the `wasm-build` ivpm dep-set on
#* PATH. Source it; do not execute it.
#*
#*   source scripts/wasm-env.sh
#*   emcmake cmake ...
#*
#* EM_CONFIG and EM_CACHE are pointed inside packages/emsdk deliberately
#* (ts-wasm-impl-plan.md §1.4). emcc compiles sysroot libraries -- libc++,
#* libembind -- on first use, and a $HOME-relative cache is how a build ends up
#* warm on a developer workstation and cold in every CI runner.
#****************************************************************************

_wasm_env_this="${BASH_SOURCE[0]:-$0}"
PSSPARSER_ROOT="$(cd "$(dirname "${_wasm_env_this}")/.." && pwd)"
unset _wasm_env_this

EMSDK_DIR="${PSSPARSER_ROOT}/packages/emsdk"

# The upstream tarball has a single top-level `install/` directory. Whether
# that survives depends on who unpacked it -- ivpm's archive handler may strip
# it, a manual `tar --strip-components=1` does -- and the difference is not
# worth caring about at every call site, so it is absorbed here.
if [ -x "${EMSDK_DIR}/install/emscripten/emcc" ]; then
    EMSDK_DIR="${EMSDK_DIR}/install"
fi

if [ ! -x "${EMSDK_DIR}/emscripten/emcc" ]; then
    echo "wasm-env.sh: no Emscripten toolchain at ${EMSDK_DIR}" >&2
    echo "             run: ivpm update -d wasm-build" >&2
    return 1 2>/dev/null || exit 1
fi

export EMSDK="${EMSDK_DIR}"

# The config is written beside the toolchain on first use rather than shipped,
# because it has to name absolute paths and the toolchain's location is not
# known until it has been fetched.
if [ ! -f "${EMSDK_DIR}/emscripten.config" ]; then
    cat > "${EMSDK_DIR}/emscripten.config" <<'EOF'
import os
# Generated by scripts/wasm-env.sh. Every path is derived from this file's own
# location rather than from $HOME, so a CI runner and a developer workstation
# resolve to the same tree.
EMSDK = os.path.dirname(os.path.abspath(__file__))

LLVM_ROOT = os.path.join(EMSDK, 'bin')
BINARYEN_ROOT = EMSDK
EMSCRIPTEN_ROOT = os.path.join(EMSDK, 'emscripten')
NODE_JS = os.environ.get('EM_NODE_JS', 'node')
CACHE = os.path.join(EMSDK, 'cache')
EOF
fi

export EM_CONFIG="${EMSDK_DIR}/emscripten.config"
export EM_CACHE="${EMSDK_DIR}/cache"
export PATH="${EMSDK_DIR}/emscripten:${EMSDK_DIR}/bin:${PATH}"

# emcc drives node for its own tooling; prefer the ivpm-managed runtime when
# one is present so the build does not depend on whatever `node` the developer
# happens to have first on PATH.
if [ -x "${PSSPARSER_ROOT}/packages/node/bin/node" ]; then
    export EM_NODE_JS="${PSSPARSER_ROOT}/packages/node/bin/node"
    export PATH="${PSSPARSER_ROOT}/packages/node/bin:${PATH}"
fi

unset EMSDK_DIR
