#!/bin/bash
#****************************************************************************
#* wasm-env.sh
#*
#* Put the Emscripten toolchain fetched by the `wasm-build` ivpm dep-set on
#* PATH. Source it; do not execute it.
#*
#*   source scripts/wasm-env.sh
#*   emcmake cmake ...
#*
#* EM_CONFIG and EM_CACHE are pointed at a project-local directory
#* (ts-wasm-impl-plan.md §1.4). emcc compiles sysroot libraries -- libc++,
#* libembind -- on first use, and a $HOME-relative cache is how a build ends up
#* warm on a developer workstation and cold in every CI runner.
#*
#* Project-local rather than beside the toolchain, which is where they used to
#* go. Verified 2026-09-07: the `wasm-build` dep declares `cache: true`, so ivpm
#* does not unpack into packages/emsdk -- it symlinks packages/emsdk at a shared
#* entry under ~/.ivpm/cache keyed by the toolchain version. Writing the config
#* and the sysroot cache through that symlink mutates storage owned by another
#* tool and shared with every other project on the machine, and fails outright
#* on a CI runner that mounts the ivpm cache read-only.
#****************************************************************************

_wasm_env_this="${BASH_SOURCE[0]:-$0}"
PSSPARSER_ROOT="$(cd "$(dirname "${_wasm_env_this}")/.." && pwd)"
unset _wasm_env_this

EMSDK_DIR="${PSSPARSER_ROOT}/packages/emsdk"

# The upstream tarball has a single top-level `install/` directory. ivpm's
# archive handler strips it (verified 2026-09-07: the fetched tree is
# packages/emsdk/{bin,emscripten,lib}); a hand-unpack without
# --strip-components=1 does not. The difference is not worth caring about at
# every call site, so it is absorbed here.
if [ -x "${EMSDK_DIR}/install/emscripten/emcc" ]; then
    EMSDK_DIR="${EMSDK_DIR}/install"
fi

if [ ! -x "${EMSDK_DIR}/emscripten/emcc" ]; then
    echo "wasm-env.sh: no Emscripten toolchain at ${EMSDK_DIR}" >&2
    echo "             run: ivpm update -d default-dev -d wasm-build" >&2
    return 1 2>/dev/null || exit 1
fi

export EMSDK="${EMSDK_DIR}"

# Writable state -- the generated config and the sysroot cache -- lives here,
# never inside the toolchain tree, which may be a symlink into ivpm's shared
# cache. Rewritten on every source: the toolchain path is baked into it, and a
# stale config left behind by a `--refresh-all` that moved the toolchain is a
# far more confusing failure than a one-line rewrite is a cost.
EM_STATE_DIR="${PSSPARSER_ROOT}/.emsdk"
mkdir -p "${EM_STATE_DIR}/cache"

cat > "${EM_STATE_DIR}/emscripten.config" <<EOF
import os
# Generated by scripts/wasm-env.sh -- do not edit. Paths are absolute and
# derived from the project root rather than from \$HOME, so a CI runner and a
# developer workstation resolve to the same tree.
EMSDK = '${EMSDK_DIR}'

LLVM_ROOT = os.path.join(EMSDK, 'bin')
BINARYEN_ROOT = EMSDK
EMSCRIPTEN_ROOT = os.path.join(EMSDK, 'emscripten')
NODE_JS = os.environ.get('EM_NODE_JS', 'node')
CACHE = '${EM_STATE_DIR}/cache'
EOF

export EM_CONFIG="${EM_STATE_DIR}/emscripten.config"
export EM_CACHE="${EM_STATE_DIR}/cache"
export PATH="${EMSDK_DIR}/emscripten:${EMSDK_DIR}/bin:${PATH}"

# emcc drives node for its own tooling; prefer the ivpm-managed runtime when
# one is present so the build does not depend on whatever `node` the developer
# happens to have first on PATH.
if [ -x "${PSSPARSER_ROOT}/packages/node/bin/node" ]; then
    export EM_NODE_JS="${PSSPARSER_ROOT}/packages/node/bin/node"
    export PATH="${PSSPARSER_ROOT}/packages/node/bin:${PATH}"
fi

unset EMSDK_DIR EM_STATE_DIR
