name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run docker
      uses: docker://quay.io/pypa/manylinux2010_x86_64
      with:
        entrypoint: /github/workspace/.github/workflows/pypi.sh

  ci-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install uuid
      run: brew install ossp-uuid
    - name: Install dependencies
      run: |
        python -m pip install --upgrade ivpm
        python -m ivpm update -r requirements_ci.txt
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

