name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  ci-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build 
      run: |
        python -m pip install ivpm
        mkdir build
        cd build
        python -m ivpm update -r requirements_ci.txt
        cmake .. -GNinja
        ninja


