name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  ci-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v1
    - name: Install additional build dependencies
      run: |
        yum install -y libuuid-devel
        yum install -y java-1.8.0-openjdk-devel
        for py in cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310; do
          /opt/python/${py}/bin/python -m pip install ninja wheel cython
        done
    - name: Fetch source dependencies
      run: |
        export IVPM_PYTHON=/opt/python/cp37-cp37m/bin/python
        ${IVPM_PYTHON} -m pip install ivpm twine auditwheel
        ${IVPM_PYTHON} -m ivpm update -a
    - name: Build packages
      run: |
        mkdir build
        cd build
        cmake ..
        make
#        export BUILD_NUM=$GITHUB_RUN_ID
#        for py in cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310; do
#          /opt/python/${py}/bin/python setup.py bdist_wheel
#        done
    - name: Audit Wheels
      run: |
        for whl in dist/*.whl; do
          /opt/python/cp37-cp37m/bin/auditwheel repair $whl
          rm $whl
        done
        cp wheelhouse/*.whl dist
        #    - name: Publish to PyPi
        #      if: startsWith(github.ref, 'refs/heads/main')
        #      uses: pypa/gh-action-pypi-publish@release/v1
        #      with:
        #        user: __token__
        #        password: ${{ secrets.PYPI_API_TOKEN }}

        #  ci-osx:
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Setup java
#      uses: actions/setup-java@v1
#      with:
#        java-version: '11.0.x'
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.9'
#    - name: Install uuid
#      run: brew install ossp-uuid
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade ivpm
#        python -m ivpm update -r requirements_ci.txt
#    - name: Build
#      run: |
#       mkdir build
#        cd build
#        cmake ..
#        make
#    - name: Upload to PyPi
#      run: |
#        echo "TODO: upload to PyPi"

  ci-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Packages
      run: |
        python -m pip install ivpm twine cython ninja wheel
        python -m ivpm update -a
    - name: Build 
      run: |
        mkdir build
        cd build
        cmake .. -GNinja
        ninja


